# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdad9216bb8b5a85c4564ba38fc1665f87b8dbb72ae46456622a3a29093859064b588386b18836001a1449f5fd2b7653466177774ae03b6914f8dc5a000d97fc

test:
  secret_key_base: 9f315f86ff21213d57f5f6795f1ae2eab9ff8adc7becac6c6c6c425b6d02f8daa3bf9cdf152e242a8dd8da07de029859ee264d5c309dddef61b92f72634d1b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
